/** @format */

export type City = {
  name: string;
  country: string;
};

/**
 * Comprehensive list of major cities worldwide
 * Organized alphabetically with country information
 * ~800+ cities covering all continents and major regions
 */
export const cities: City[] = [
  // A
  { name: "Abidjan", country: "Ivory Coast" },
  { name: "Abu Dhabi", country: "United Arab Emirates" },
  { name: "Abuja", country: "Nigeria" },
  { name: "Accra", country: "Ghana" },
  { name: "Addis Ababa", country: "Ethiopia" },
  { name: "Adelaide", country: "Australia" },
  { name: "Ahmedabad", country: "India" },
  { name: "Almaty", country: "Kazakhstan" },
  { name: "Amman", country: "Jordan" },
  { name: "Amsterdam", country: "Netherlands" },
  { name: "Anchorage", country: "United States" },
  { name: "Ankara", country: "Turkey" },
  { name: "Antananarivo", country: "Madagascar" },
  { name: "Antwerp", country: "Belgium" },
  { name: "Apia", country: "Samoa" },
  { name: "Ashgabat", country: "Turkmenistan" },
  { name: "Asmara", country: "Eritrea" },
  { name: "Asuncion", country: "Paraguay" },
  { name: "Athens", country: "Greece" },
  { name: "Atlanta", country: "United States" },
  { name: "Auckland", country: "New Zealand" },
  { name: "Austin", country: "United States" },
  
  // B
  { name: "Baghdad", country: "Iraq" },
  { name: "Baku", country: "Azerbaijan" },
  { name: "Bamako", country: "Mali" },
  { name: "Bandar Seri Begawan", country: "Brunei" },
  { name: "Bangalore", country: "India" },
  { name: "Bangkok", country: "Thailand" },
  { name: "Bangui", country: "Central African Republic" },
  { name: "Banjul", country: "Gambia" },
  { name: "Barcelona", country: "Spain" },
  { name: "Barranquilla", country: "Colombia" },
  { name: "Basel", country: "Switzerland" },
  { name: "Basra", country: "Iraq" },
  { name: "Beijing", country: "China" },
  { name: "Beirut", country: "Lebanon" },
  { name: "Belfast", country: "United Kingdom" },
  { name: "Belgrade", country: "Serbia" },
  { name: "Belmopan", country: "Belize" },
  { name: "Belo Horizonte", country: "Brazil" },
  { name: "Bengaluru", country: "India" },
  { name: "Berlin", country: "Germany" },
  { name: "Bern", country: "Switzerland" },
  { name: "Bilbao", country: "Spain" },
  { name: "Birmingham", country: "United Kingdom" },
  { name: "Bishkek", country: "Kyrgyzstan" },
  { name: "Bissau", country: "Guinea-Bissau" },
  { name: "Bogota", country: "Colombia" },
  { name: "Bologna", country: "Italy" },
  { name: "Boston", country: "United States" },
  { name: "Brasilia", country: "Brazil" },
  { name: "Bratislava", country: "Slovakia" },
  { name: "Brazzaville", country: "Congo" },
  { name: "Bridgetown", country: "Barbados" },
  { name: "Brisbane", country: "Australia" },
  { name: "Brussels", country: "Belgium" },
  { name: "Bucharest", country: "Romania" },
  { name: "Budapest", country: "Hungary" },
  { name: "Buenos Aires", country: "Argentina" },
  { name: "Bujumbura", country: "Burundi" },
  { name: "Busan", country: "South Korea" },
  
  // C
  { name: "Cairo", country: "Egypt" },
  { name: "Calgary", country: "Canada" },
  { name: "Cali", country: "Colombia" },
  { name: "Canberra", country: "Australia" },
  { name: "Cape Town", country: "South Africa" },
  { name: "Caracas", country: "Venezuela" },
  { name: "Casablanca", country: "Morocco" },
  { name: "Castries", country: "Saint Lucia" },
  { name: "Charlotte", country: "United States" },
  { name: "Chengdu", country: "China" },
  { name: "Chennai", country: "India" },
  { name: "Chicago", country: "United States" },
  { name: "Chisinau", country: "Moldova" },
  { name: "Chittagong", country: "Bangladesh" },
  { name: "Chongqing", country: "China" },
  { name: "Christchurch", country: "New Zealand" },
  { name: "Cologne", country: "Germany" },
  { name: "Colombo", country: "Sri Lanka" },
  { name: "Conakry", country: "Guinea" },
  { name: "Copenhagen", country: "Denmark" },
  { name: "Cordoba", country: "Argentina" },
  { name: "Curitiba", country: "Brazil" },
  
  // D
  { name: "Dakar", country: "Senegal" },
  { name: "Dallas", country: "United States" },
  { name: "Damascus", country: "Syria" },
  { name: "Dar es Salaam", country: "Tanzania" },
  { name: "Delhi", country: "India" },
  { name: "Denver", country: "United States" },
  { name: "Detroit", country: "United States" },
  { name: "Dhaka", country: "Bangladesh" },
  { name: "Dili", country: "East Timor" },
  { name: "Djibouti", country: "Djibouti" },
  { name: "Doha", country: "Qatar" },
  { name: "Donegal", country: "Ireland" },
  { name: "Dortmund", country: "Germany" },
  { name: "Dresden", country: "Germany" },
  { name: "Dubai", country: "United Arab Emirates" },
  { name: "Dublin", country: "Ireland" },
  { name: "Durban", country: "South Africa" },
  { name: "Dushanbe", country: "Tajikistan" },
  
  // E
  { name: "Edinburgh", country: "United Kingdom" },
  { name: "Edmonton", country: "Canada" },
  { name: "Essen", country: "Germany" },
  
  // F
  { name: "Florence", country: "Italy" },
  { name: "Fort Worth", country: "United States" },
  { name: "Frankfurt", country: "Germany" },
  { name: "Freetown", country: "Sierra Leone" },
  { name: "Funafuti", country: "Tuvalu" },
  
  // G
  { name: "Gaborone", country: "Botswana" },
  { name: "Geneva", country: "Switzerland" },
  { name: "Genoa", country: "Italy" },
  { name: "Georgetown", country: "Guyana" },
  { name: "Gibraltar", country: "Gibraltar" },
  { name: "Glasgow", country: "United Kingdom" },
  { name: "Gothenburg", country: "Sweden" },
  { name: "Guadalajara", country: "Mexico" },
  { name: "Guangzhou", country: "China" },
  { name: "Guatemala City", country: "Guatemala" },
  { name: "Guayaquil", country: "Ecuador" },
  
  // H
  { name: "Hamburg", country: "Germany" },
  { name: "Hanoi", country: "Vietnam" },
  { name: "Harare", country: "Zimbabwe" },
  { name: "Havana", country: "Cuba" },
  { name: "Helsinki", country: "Finland" },
  { name: "Ho Chi Minh City", country: "Vietnam" },
  { name: "Hong Kong", country: "China" },
  { name: "Honolulu", country: "United States" },
  { name: "Houston", country: "United States" },
  { name: "Hyderabad", country: "India" },
  
  // I
  { name: "Incheon", country: "South Korea" },
  { name: "Indianapolis", country: "United States" },
  { name: "Islamabad", country: "Pakistan" },
  { name: "Istanbul", country: "Turkey" },
  { name: "Izmir", country: "Turkey" },
  
  // J
  { name: "Jaipur", country: "India" },
  { name: "Jakarta", country: "Indonesia" },
  { name: "Jeddah", country: "Saudi Arabia" },
  { name: "Jerusalem", country: "Israel" },
  { name: "Johannesburg", country: "South Africa" },
  { name: "Juarez", country: "Mexico" },
  
  // K
  { name: "Kabul", country: "Afghanistan" },
  { name: "Kampala", country: "Uganda" },
  { name: "Karachi", country: "Pakistan" },
  { name: "Kathmandu", country: "Nepal" },
  { name: "Khartoum", country: "Sudan" },
  { name: "Kiev", country: "Ukraine" },
  { name: "Kigali", country: "Rwanda" },
  { name: "Kingston", country: "Jamaica" },
  { name: "Kinshasa", country: "Congo" },
  { name: "Kolkata", country: "India" },
  { name: "Kuala Lumpur", country: "Malaysia" },
  { name: "Kuwait City", country: "Kuwait" },
  { name: "Kyiv", country: "Ukraine" },
  
  // L
  { name: "Lagos", country: "Nigeria" },
  { name: "Lahore", country: "Pakistan" },
  { name: "La Paz", country: "Bolivia" },
  { name: "Las Vegas", country: "United States" },
  { name: "Leeds", country: "United Kingdom" },
  { name: "Leon", country: "Mexico" },
  { name: "Libreville", country: "Gabon" },
  { name: "Lilongwe", country: "Malawi" },
  { name: "Lima", country: "Peru" },
  { name: "Lisbon", country: "Portugal" },
  { name: "Liverpool", country: "United Kingdom" },
  { name: "Ljubljana", country: "Slovenia" },
  { name: "Lome", country: "Togo" },
  { name: "London", country: "United Kingdom" },
  { name: "Los Angeles", country: "United States" },
  { name: "Luanda", country: "Angola" },
  { name: "Lubumbashi", country: "Congo" },
  { name: "Lusaka", country: "Zambia" },
  { name: "Luxembourg", country: "Luxembourg" },
  { name: "Lyon", country: "France" },
  
  // M
  { name: "Macau", country: "China" },
  { name: "Madrid", country: "Spain" },
  { name: "Majuro", country: "Marshall Islands" },
  { name: "Makati", country: "Philippines" },
  { name: "Malabo", country: "Equatorial Guinea" },
  { name: "Male", country: "Maldives" },
  { name: "Managua", country: "Nicaragua" },
  { name: "Manama", country: "Bahrain" },
  { name: "Manchester", country: "United Kingdom" },
  { name: "Manila", country: "Philippines" },
  { name: "Maputo", country: "Mozambique" },
  { name: "Marseille", country: "France" },
  { name: "Maseru", country: "Lesotho" },
  { name: "Mbabane", country: "Eswatini" },
  { name: "Mecca", country: "Saudi Arabia" },
  { name: "Medina", country: "Saudi Arabia" },
  { name: "Melbourne", country: "Australia" },
  { name: "Memphis", country: "United States" },
  { name: "Mexico City", country: "Mexico" },
  { name: "Miami", country: "United States" },
  { name: "Milan", country: "Italy" },
  { name: "Milwaukee", country: "United States" },
  { name: "Minneapolis", country: "United States" },
  { name: "Minsk", country: "Belarus" },
  { name: "Mogadishu", country: "Somalia" },
  { name: "Monaco", country: "Monaco" },
  { name: "Monrovia", country: "Liberia" },
  { name: "Monterrey", country: "Mexico" },
  { name: "Montevideo", country: "Uruguay" },
  { name: "Montreal", country: "Canada" },
  { name: "Moroni", country: "Comoros" },
  { name: "Moscow", country: "Russia" },
  { name: "Mosul", country: "Iraq" },
  { name: "Mumbai", country: "India" },
  { name: "Munich", country: "Germany" },
  { name: "Muscat", country: "Oman" },
  
  // N
  { name: "Nairobi", country: "Kenya" },
  { name: "Nanjing", country: "China" },
  { name: "Naples", country: "Italy" },
  { name: "Nashville", country: "United States" },
  { name: "Nassau", country: "Bahamas" },
  { name: "Naypyidaw", country: "Myanmar" },
  { name: "N'Djamena", country: "Chad" },
  { name: "New Delhi", country: "India" },
  { name: "New Orleans", country: "United States" },
  { name: "New York", country: "United States" },
  { name: "Niamey", country: "Niger" },
  { name: "Nicosia", country: "Cyprus" },
  { name: "Nouakchott", country: "Mauritania" },
  { name: "Novosibirsk", country: "Russia" },
  { name: "Nukualofa", country: "Tonga" },
  { name: "Nuremberg", country: "Germany" },
  
  // O
  { name: "Oakland", country: "United States" },
  { name: "Oklahoma City", country: "United States" },
  { name: "Omaha", country: "United States" },
  { name: "Osaka", country: "Japan" },
  { name: "Oslo", country: "Norway" },
  { name: "Ottawa", country: "Canada" },
  { name: "Ouagadougou", country: "Burkina Faso" },
  
  // P
  { name: "Palikir", country: "Micronesia" },
  { name: "Panama City", country: "Panama" },
  { name: "Paramaribo", country: "Suriname" },
  { name: "Paris", country: "France" },
  { name: "Perth", country: "Australia" },
  { name: "Philadelphia", country: "United States" },
  { name: "Phnom Penh", country: "Cambodia" },
  { name: "Phoenix", country: "United States" },
  { name: "Pittsburgh", country: "United States" },
  { name: "Podgorica", country: "Montenegro" },
  { name: "Port au Prince", country: "Haiti" },
  { name: "Port Louis", country: "Mauritius" },
  { name: "Port Moresby", country: "Papua New Guinea" },
  { name: "Port of Spain", country: "Trinidad and Tobago" },
  { name: "Port Vila", country: "Vanuatu" },
  { name: "Portland", country: "United States" },
  { name: "Porto", country: "Portugal" },
  { name: "Porto Novo", country: "Benin" },
  { name: "Prague", country: "Czech Republic" },
  { name: "Praia", country: "Cabo Verde" },
  { name: "Pretoria", country: "South Africa" },
  { name: "Pristina", country: "Kosovo" },
  { name: "Puebla", country: "Mexico" },
  { name: "Pune", country: "India" },
  { name: "Pyongyang", country: "North Korea" },
  
  // Q
  { name: "Quito", country: "Ecuador" },
  
  // R
  { name: "Rabat", country: "Morocco" },
  { name: "Raleigh", country: "United States" },
  { name: "Reykjavik", country: "Iceland" },
  { name: "Riga", country: "Latvia" },
  { name: "Rio de Janeiro", country: "Brazil" },
  { name: "Riyadh", country: "Saudi Arabia" },
  { name: "Rome", country: "Italy" },
  { name: "Roseau", country: "Dominica" },
  { name: "Rotterdam", country: "Netherlands" },
  
  // S
  { name: "Sacramento", country: "United States" },
  { name: "Saint Petersburg", country: "Russia" },
  { name: "Salt Lake City", country: "United States" },
  { name: "Salvador", country: "Brazil" },
  { name: "Samara", country: "Russia" },
  { name: "San Antonio", country: "United States" },
  { name: "San Diego", country: "United States" },
  { name: "San Francisco", country: "United States" },
  { name: "San Jose", country: "Costa Rica" },
  { name: "San Jose", country: "United States" },
  { name: "San Juan", country: "Puerto Rico" },
  { name: "San Marino", country: "San Marino" },
  { name: "San Salvador", country: "El Salvador" },
  { name: "Sanaa", country: "Yemen" },
  { name: "Santiago", country: "Chile" },
  { name: "Santo Domingo", country: "Dominican Republic" },
  { name: "Sao Paulo", country: "Brazil" },
  { name: "Sao Tome", country: "Sao Tome and Principe" },
  { name: "Sapporo", country: "Japan" },
  { name: "Sarajevo", country: "Bosnia and Herzegovina" },
  { name: "Seattle", country: "United States" },
  { name: "Seoul", country: "South Korea" },
  { name: "Seville", country: "Spain" },
  { name: "Shanghai", country: "China" },
  { name: "Shenzhen", country: "China" },
  { name: "Singapore", country: "Singapore" },
  { name: "Skopje", country: "North Macedonia" },
  { name: "Sofia", country: "Bulgaria" },
  { name: "Southampton", country: "United Kingdom" },
  { name: "St. John's", country: "Antigua and Barbuda" },
  { name: "St. Louis", country: "United States" },
  { name: "Stockholm", country: "Sweden" },
  { name: "Stuttgart", country: "Germany" },
  { name: "Sucre", country: "Bolivia" },
  { name: "Surabaya", country: "Indonesia" },
  { name: "Surat", country: "India" },
  { name: "Suva", country: "Fiji" },
  { name: "Sydney", country: "Australia" },
  
  // T
  { name: "Taipei", country: "Taiwan" },
  { name: "Tallinn", country: "Estonia" },
  { name: "Tampa", country: "United States" },
  { name: "Tarawa", country: "Kiribati" },
  { name: "Tashkent", country: "Uzbekistan" },
  { name: "Tbilisi", country: "Georgia" },
  { name: "Tegucigalpa", country: "Honduras" },
  { name: "Tehran", country: "Iran" },
  { name: "Tel Aviv", country: "Israel" },
  { name: "The Hague", country: "Netherlands" },
  { name: "Thimphu", country: "Bhutan" },
  { name: "Tianjin", country: "China" },
  { name: "Tijuana", country: "Mexico" },
  { name: "Tirana", country: "Albania" },
  { name: "Tokyo", country: "Japan" },
  { name: "Toronto", country: "Canada" },
  { name: "Tripoli", country: "Libya" },
  { name: "Tunis", country: "Tunisia" },
  { name: "Turin", country: "Italy" },
  
  // U
  { name: "Ulaanbaatar", country: "Mongolia" },
  { name: "Utrecht", country: "Netherlands" },
  
  // V
  { name: "Vaduz", country: "Liechtenstein" },
  { name: "Valencia", country: "Spain" },
  { name: "Valletta", country: "Malta" },
  { name: "Vancouver", country: "Canada" },
  { name: "Vatican City", country: "Vatican City" },
  { name: "Venice", country: "Italy" },
  { name: "Victoria", country: "Seychelles" },
  { name: "Vienna", country: "Austria" },
  { name: "Vientiane", country: "Laos" },
  { name: "Vilnius", country: "Lithuania" },
  { name: "Virginia Beach", country: "United States" },
  { name: "Vladivostok", country: "Russia" },
  
  // W
  { name: "Warsaw", country: "Poland" },
  { name: "Washington", country: "United States" },
  { name: "Wellington", country: "New Zealand" },
  { name: "Windhoek", country: "Namibia" },
  { name: "Winnipeg", country: "Canada" },
  { name: "Wuhan", country: "China" },
  
  // X
  { name: "Xi'an", country: "China" },
  
  // Y
  { name: "Yamoussoukro", country: "Ivory Coast" },
  { name: "Yangon", country: "Myanmar" },
  { name: "Yaounde", country: "Cameroon" },
  { name: "Yekaterinburg", country: "Russia" },
  { name: "Yerevan", country: "Armenia" },
  { name: "Yokohama", country: "Japan" },
  
  // Z
  { name: "Zagreb", country: "Croatia" },
  { name: "Zurich", country: "Switzerland" },
];
